apiVersion: v1
kind: ConfigMap
metadata:
  name: thunder-config
data:
  config.yaml: |
    dynamo:
      endpoint: dynamodb.us-east-1.amazonaws.com
      region: us-east-1
      tableName: pilot-users-test

    email:
      endpoint: email.us-east-1.amazonaws.com
      region: us-east-1
      fromAddress: noreply@sanctionco.com

    approvedKeys:
      - application: application
        secret: secret

    server:
      applicationConnectors:
        - type: http
          port: 8080
      adminConnectors:
        - type: http
          port: 8081
